server:
    port: 8080

spring:
    data:
        redis:
            host: localhost
            port: 6379
    jpa:        
        hibernate:       
            jdbc:
                time_zone: Asia/Seoul     
            ddl-auto: none
            naming: 
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            show_sql: true    
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
    datasource:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        url: jdbc:log4jdbc:mysql://localhost:3306/SAFETY?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
        username: root
        password: password
    security:
        oauth2:
            client:
                registration:
                    naver:
                        client-id: test
                        client-secret: test
                        redirect-uri: http://localhost:8080/api/local/oauth2/code/naver
                        authorization-grant-type: authorization_code
                        client-name: naver
                        scope:
                            - email
                            - name
                    kakao:
                        client-id: test
                        client-secret: test
                        redirect-uri: http://localhost:8080/api/local/oauth2/code/kakao
                        client-authentication-method: client_secret_post
                        authorization-grant-type: authorization_code
                        client-name: kakao
                        scope:
                            - profile_nickname
                            - profile_image
                provider:
                    naver:
                        authorization-uri: https://nid.naver.com/oauth2.0/authorize
                        token-uri: https://nid.naver.com/oauth2.0/token
                        user-info-uri: https://openapi.naver.com/v1/nid/me
                        user-name-attribute: response
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-name-attribute: id
    
            


data:
    portal:
        law-key: public-data-portal-key