CREATE TABLE USERS (
    USERNAME VARCHAR(255) NOT NULL PRIMARY KEY,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255),
    REFRESH_TOKEN VARCHAR(255),
    ENABLED BOOLEAN NOT NULL,
    ACCOUNT_NON_LOCK BOOLEAN NOT NULL,
    ACCOUNT_NON_EXPRIED BOOLEAN NOT NULL,
    PASS_FAIL_COUNT INT NOT NULL,
    CREATE_DT DATETIME NOT NULL DEFAULT current_timestamp(),
    UPDATE_DT DATETIME NOT NULL DEFAULT current_timestamp(),
    DELETE_DT DATETIME DEFAULT NULL,
    FCM_DEVICE_TOKEN VARCHAR(255) DEFAULT NULL,
    PROFILE_IMG_URL VARCHAR(255) DEFAULT NULL
);

CREATE TABLE USERS_DTL (
    USERNAME VARCHAR(255) NOT NULL PRIMARY KEY,
    NICKNAME VARCHAR(255),
    NAME VARCHAR(255) NOT NULL,
    HPNO VARCHAR(255),
    CONSTRAINT FK_USERS_DTL_USERNAME FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME)
);

CREATE TABLE AUTHORITIES (
    USERNAME VARCHAR(255) NOT NULL,
    AUTHORITY VARCHAR(255) NOT NULL,
    PRIMARY KEY (USERNAME, AUTHORITY),
    CONSTRAINT FK_AUTHORITIES_USERNAME FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME)
);

CREATE TABLE LOGGING (
    IDX INT AUTO_INCREMENT PRIMARY KEY,
    TYPE VARCHAR(20) NOT NULL,
    USERNAME VARCHAR(500),
    IP VARCHAR(25) NOT NULL,
    MESSAGE VARCHAR(100),
    CREDENTIALS VARCHAR(500),
    CREATE_DT DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE LAW (
    LAW_IDX BIGINT AUTO_INCREMENT PRIMARY KEY,
    CATEGORY VARCHAR(255) NOT NULL,
    CONTENT LONGTEXT NOT NULL,
    HIGHLIGHT_CONTENT LONGTEXT NOT NULL,
    DOC_ID VARCHAR(255) NOT NULL,
    SCORE DOUBLE NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    CREATE_DT DATE NOT NULL,
    LAST_UPDATE_DT DATE NOT NULL,
    VIEW BIGINT NOT NULL DEFAULT '0',
);

CREATE TABLE `COMMENT` (
  `COMMENT_IDX` BIGINT NOT NULL AUTO_INCREMENT,
  `CREATE_DT` DATETIME(6) NOT NULL,
  `LAW_IDX` BIGINT DEFAULT NULL,
  `UPDATE_DT` DATETIME(6) NOT NULL,
  `CONTENT` VARCHAR(255) NOT NULL,
  `CREATE_USER` VARCHAR(255) NOT NULL,
  `UPDATE_USER` VARCHAR(255) NOT NULL,
  `NICKNAME` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`COMMENT_IDX`),
  KEY `FKn2heieuti5nhddmn5tpm3ys8s` (`LAW_IDX`),
  CONSTRAINT `FKn2heieuti5nhddmn5tpm3ys8s` FOREIGN KEY (`LAW_IDX`) REFERENCES `LAW` (`LAW_IDX`)
)

CREATE TABLE SCHEDULER_UPDATE_DATE (
    NAME VARCHAR(255) NOT NULL,
    UPDATE_DT DATE NOT NULL,
    STATUS VARCHAR(255) NOT NULL,
    PRIMARY KEY (NAME)
);

CREATE TABLE TOKEN_BLACK (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL,
    REFRESH_TOKEN VARCHAR(255) NOT NULL,
    CREATE_DT DATETIME NOT NULL
);

CREATE TABLE MESSAGE (
    MESSAGE_IDX BIGINT AUTO_INCREMENT PRIMARY KEY,
    MESSAGE_TYPE ENUM('LINK_CERT', 'UPDATE_CERT', 'GUIDE') NOT NULL,
    CONTENT LONGTEXT NOT NULL,
    CERT_NUM VARCHAR(255) NOT NULL,
    PHONE_NUM VARCHAR(255) NOT NULL,
    CERT_YN BOOLEAN NOT NULL,
    CREATE_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE USER_LAW_READ_HISTORY (
    USER_LAW_READ_HISTORY_IDX BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL,
    LAW_IDX BIGINT NOT NULL,
    CREATE_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE DAY_RANK (
    DAY_RANK_IDX BIGINT AUTO_INCREMENT PRIMARY KEY,
    KEYWORD VARCHAR(255),
    CREATE_DT DATETIME
);

CREATE TABLE BOARD (
    BOARD_IDX BIGINT NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(255) NOT NULL,
    CONTENT TEXT NOT NULL,
    CREATE_DT DATETIME NOT NULL,
    UPDATE_DT DATETIME NOT NULL,
    CREATE_USER VARCHAR(255) NOT NULL,
    UPDATE_USER VARCHAR(255),
    PRIMARY KEY (BOARD_IDX)
);

CREATE TABLE BOARD_COMMENT (
    BOARD_COMMENT_IDX BIGINT NOT NULL AUTO_INCREMENT,
    CONTENT TEXT NOT NULL,
    PARENT_IDX BIGINT,
    CREATE_DT DATETIME,
    UPDATE_DT DATETIME,
    CREATE_USER VARCHAR(255) NOT NULL,
    UPDATE_USER VARCHAR(255),
    BOARD_IDX BIGINT NOT NULL,
    PRIMARY KEY (BOARD_COMMENT_IDX),
    FOREIGN KEY (BOARD_IDX) REFERENCES BOARD (BOARD_IDX) ON DELETE CASCADE
);

CREATE TABLE `BOARD_HEART_REFRENCE` (
  `BOARD_HEART_REFRENCE_IDX` bigint(20) NOT NULL AUTO_INCREMENT,
  `BOARD_IDX` bigint(20) NOT NULL,
  `USERNAME` varchar(255) NOT NULL,
  PRIMARY KEY (`BOARD_HEART_REFRENCE_IDX`),
  KEY `FK5jmo5r39i52xv4irqhfbmxxo1` (`BOARD_IDX`),
  KEY `FKk9oxpjlvw3rccrjxm5pqs7jeb` (`USERNAME`),
  CONSTRAINT `FK5jmo5r39i52xv4irqhfbmxxo1` FOREIGN KEY (`BOARD_IDX`) REFERENCES `BOARD` (`BOARD_IDX`),
  CONSTRAINT `FKk9oxpjlvw3rccrjxm5pqs7jeb` FOREIGN KEY (`USERNAME`) REFERENCES `USERS` (`USERNAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE NOTIFICATION_AGREE (
    NOTIFICATION_AGREE_IDX BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOTIFICATION_TYPE ENUM('QNA_NOTIFICATION') NOT NULL,
    CREATE_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DELETE_DT TIMESTAMP NULL,
    NOTIFICATION_USERNAME VARCHAR(255) NOT NULL,
    CONSTRAINT fk_notification_username FOREIGN KEY (NOTIFICATION_USERNAME) REFERENCES USERS(USERNAME)
);

CREATE TABLE LAW_UPDATE_HISTORY (
    LAW_UPDATE_HISTORY_IDX BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    LAW_IDX BIGINT NOT NULL,
    OLD_CONTENT LONGTEXT NOT NULL,
    NEW_CONTENT LONGTEXT NOT NULL,
    CREATE_DT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_LAW_UPDATE_HISTORY_LAW FOREIGN KEY (LAW_IDX) REFERENCES LAW(LAW_IDX)
);